import { Metadata, ResolvingMetadata } from "next";
import { siteConfig } from "@/lib/seo";
import { createClient } from "@/lib/supabase/server";
import EditorClient from "./EditorClient";

type Props = {
    params: { id: string }
    searchParams: { [key: string]: string | string[] | undefined }
}

export async function generateMetadata(
    { params, searchParams }: Props,
    parent: ResolvingMetadata
): Promise<Metadata> {
    const id = params.id

    const supabase = await createClient();
    const { data: project } = await supabase
        .from('projects')
        .select('video_title, video_url')
        .eq('id', id)
        .single();

    return {
        title: project?.video_title || `Project Editor - ${siteConfig.name}`,
        openGraph: {
            title: project?.video_title ? `${project.video_title} | ViralKlip` : `Editing Project - ViralKlip`,
            description: `Check out this viral clip generated by AI.`,
            videos: project?.video_url ? [project.video_url] : undefined
        }
    }
}

export default function EditorPage({ params }: { params: { id: string } }) {
    return <EditorClient id={params.id} />
}
