// This file will be auto-generated by running: npm run db:types
// For now, using a basic placeholder structure

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            users: {
                Row: {
                    id: string
                    email: string
                    name: string | null
                    avatar_url: string | null
                    subscription_tier: string
                    credits_remaining: number
                    credits_reset_date: string | null
                    stripe_customer_id: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    email: string
                    name?: string | null
                    avatar_url?: string | null
                    subscription_tier?: string
                    credits_remaining?: number
                    credits_reset_date?: string | null
                    stripe_customer_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    name?: string | null
                    avatar_url?: string | null
                    subscription_tier?: string
                    credits_remaining?: number
                    credits_reset_date?: string | null
                    stripe_customer_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            projects: {
                Row: {
                    id: string
                    user_id: string
                    video_url: string | null
                    video_title: string | null
                    video_duration: number | null
                    thumbnail_url: string | null
                    status: string
                    error_message: string | null
                    transcript: string | null
                    created_at: string
                    completed_at: string | null
                }
                Insert: {
                    id?: string
                    user_id: string
                    video_url?: string | null
                    video_title?: string | null
                    video_duration?: number | null
                    thumbnail_url?: string | null
                    status?: string
                    error_message?: string | null
                    transcript?: string | null
                    created_at?: string
                    completed_at?: string | null
                }
                Update: {
                    id?: string
                    user_id?: string
                    video_url?: string | null
                    video_title?: string | null
                    video_duration?: number | null
                    thumbnail_url?: string | null
                    status?: string
                    error_message?: string | null
                    transcript?: string | null
                    created_at?: string
                    completed_at?: string | null
                }
            }
            clips: {
                Row: {
                    id: string
                    project_id: string
                    clip_number: number | null
                    start_time: number | null
                    end_time: number | null
                    duration: number | null
                    transcript_snippet: string | null
                    viral_score: number | null
                    viral_reason: string | null
                    keywords: string[] | null
                    aspect_ratio: string
                    video_url: string | null
                    thumbnail_url: string | null
                    subtitle_file_url: string | null
                    caption_text: string | null
                    view_prediction: number | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    project_id: string
                    clip_number?: number | null
                    start_time?: number | null
                    end_time?: number | null
                    duration?: number | null
                    transcript_snippet?: string | null
                    viral_score?: number | null
                    viral_reason?: string | null
                    keywords?: string[] | null
                    aspect_ratio?: string
                    video_url?: string | null
                    thumbnail_url?: string | null
                    subtitle_file_url?: string | null
                    caption_text?: string | null
                    view_prediction?: number | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    project_id?: string
                    clip_number?: number | null
                    start_time?: number | null
                    end_time?: number | null
                    duration?: number | null
                    transcript_snippet?: string | null
                    viral_score?: number | null
                    viral_reason?: string | null
                    keywords?: string[] | null
                    aspect_ratio?: string
                    video_url?: string | null
                    thumbnail_url?: string | null
                    subtitle_file_url?: string | null
                    caption_text?: string | null
                    view_prediction?: number | null
                    created_at?: string
                }
            }
            // Add other tables as needed
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            [_ in never]: never
        }
    }
}
